### ISSUE TITLE
能不能在阅读模式下调用自带的查找功能

### ISSUE THREAD

**Issue by calmwaves111** [nyable/obsidian-text-finder#3]
这样就能合并成一个快捷键，比较符合直觉

**Comment by nyable** [comment]
> 这样就能合并成一个快捷键，比较符合直觉

有这个功能，默认设置应该是已经启用的。
![PixPin_2024-12-28_08-15-13](https://github.com/user-attachments/assets/e77b5cc6-5d71-4771-84d0-64a55e4980a2)
